---
- name: Apply Non-kernel Updates
  hosts: "*"
  become: true

  tasks:
     - name: upgrade all packages except kernel
       yum:
         name: '*'
         state: latest
         exclude: kernel*
        tags: all
        ignore_errors: True

     - name: upgrade all packages security related except kernel
       yum:
         name: '*'
         state: latest
         security: true
         exclude: kernel*
        tags: security
        ignore_errors: True

     - name: print play hosts that failed
       debug:
         msg: "{{ ansible_play_hosts_all|difference(ansible_play_hosts) }}"
       run_once: true
