---
- name: AIX_mksysb
  hosts: all
  become: true
  become_user: root
  vars:
    mksysb_lv: "/dev/nimvgvol2"
    mksysb_dir: "/nim/mksysb"
    NIM_Server: "p8hqnim.turnpike.iway"
    backup_repo: "/nim/mksysb"
    NFS_mount: "/mnt"
 
  tasks:
    - name: "check backup filesystem "
      aix_filesystem:
        #device: "{{ mksysb_lv }}"
        filesystem: "{{ mksysb_dir }}"
        #size: 10G
        vg: "nimvg"
        state: present
        #when: ansible_distribution == 'AIX'
 
    - name: "Mount backup filesystem"
      aix_filesystem:
        #device: "{{ mksysb_lv }}"
        vg: nimvg
        filesystem: "{{ mksysb_dir }}"
        state: mounted
 
    - name: "Run mksysb backup"
      mksysb:
        name: "{{ansible_hostname}}_mksysb_{{ansible_date_time.date}}"
        storage_path: "{{ mksysb_dir }}"
        exclude_files: yes
      when: ansible_distribution == 'AIX'

    - name: "Mount NFS"
      command: "mount {{ NIM_Server }}:{{ backup_repo }} {{ NFS_mount }}"
      register: nfsmount

    - name: "Copy files from local Directory to NFS"
      copy:
        src: '"{{ mksysb_dir }}"/"{{ansible_hostname}}_mksysb_{{ansible_date_time.date}}"'
        dest: "{{ NFS_mount }}"
        remote_src: yes
      when: nfsmount is succeeded

    - name: "unmount NFS"
      mount:
        path: "{{ NFS_mount }}"
        state: unmounted
