---
- name: Check for UNREACHABLE systems and notify
  hosts: all,!netcoolhq.turnpike.iway,!netcoolst.turnpike.iway,!dsrcpilot.turnpike.iway,!regsvrhq3.turnpike.iway
  gather_facts: true
  become: true

  tasks:
  - name: Delete old /tmp/rhSystemsDown.out
    ansible.builtin.shell: rm -rf /tmp/rhSystemsDown.out 
    delegate_to: rhansible.turnpike.iway
    run_once: true

  #- name: Pull only systems that are UNREACHABLE to variable down
  #  set_fact:
  #      down: "{{ ansible_play_hosts_all|difference(ansible_play_batch) }}"
  #  run_once: true

  - name: print play hosts that failed
    debug:
        msg: 
          - "Systems that are UNREACHABLE: "
          - "{{  ansible_play_hosts_all|difference(ansible_play_batch) }}"
    register: message
    run_once: true

  - name: Create file with list of systems that are down in dhqrh8ansible
    ansible.builtin.copy:
       content: "{{  ansible_play_hosts_all|difference(ansible_play_batch) | to_nice_json }}" 
       dest: /tmp/rhSystemsDown.out
    delegate_to: rhansible.turnpike.iway
    run_once: true

  - name: rsync /tmp/rhSystemsDown.out to p8hqnim
    ansible.builtin.shell: rsync -avh /tmp/rhSystemsDown.out root@p8hqnim:/tmp/
    delegate_to: rhansible.turnpike.iway
    run_once: true 
...
