---
- name: Take ReaR Backup
  hosts: "*"
  become: true

  tasks:
  - name: Check if ReaR is installed
    ansible.builtin.shell: rpm -qa | grep rear
    register: rear_installed 
    ignore_errors: True
    check_mode: False
    changed_when: False
    
  - name: Install ReaR if not installed
    when: rear_installed.rc == 1
    debug:
     msg: "ReaR is not installed, installing ReaR"
     ansible.builtin.yum:
        name:
        - rear
        - genisoimage
        - syslinux
     state: present

  - name: Copy ReaR config file
    file:
       path: /rearbckups/local.conf
       dest: /etc/rear
       owner: root
       group: root
       mode: 0640
       state: touch
    delegate_to: regsvrhq3.turnpike.iway


  - name: Sync ReaR config file
    when: rear_installed.rc == 1
    ansible.posix.synchronize:
      src: /rearbckups/local.conf
      dest: /etc/rear
    delegate_to: regsvrhq3.turnpike.iway

  - name: Execute ReaR Backup
    shell: rear -v mkbackup

  - name: print play hosts that failed
    debug:
        msg: "{{ ansible_play_hosts_all|difference(ansible_play_batch) }}"
    run_once: true
...
